[project]
name = "miniupnpd"
description = "an open-source UPnP daemon"

[docker]
container_name = "minimythos_run"
image = "minimythos:0.1"
workdir = "/opt/miniupnp/miniupnpd"

[build]
repo_url = "https://github.com/miniupnp/miniupnp.git"
repo_revision = "f83b5e2e21aa8dfa393ff80ea287ac4fca1a4df1"
build_dir = "miniupnpd"
build_commands = [
    "apt-get install -y libnftnl-dev libmnl-dev",
    "make -j$(nproc) ASAN=1",
]
